% CODE FOR SIMULATION OF ORIGAMI SHEETS WITH SMOOTH ELASTIC FOLDS
% AUTHOR: Edwin A. Peraza Hernandez
% 05-16-2016
% PAPER DOI: http://dx.doi.org/10.1016/j.cad.2016.05.010

function [I, O] = MAIN_MODULE(I, EL)
% MAIN MODULE TO MANAGE SIMULATION
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

cd FUNCTIONS  % CHANGING DIRECTORY TO FUNCTIONS

I = PATTERN_DATA(I,EL); % FOLD PATTERN DATA

PLOT1(I); % INITIAL PLOTS

tic
if I.parallel == 1 % USE PARALLEL for LOOPS FOR JACOBIAN
    O = ELASTIC_MODULE_P(I, EL); % ELASTIC SIMULATION MODULE
else % DO NOT USE PARALLEL for LOOPS FOR JACOBIAN
    O = ELASTIC_MODULE(I, EL); % ELASTIC SIMULATION MODULE    
end
toc
O.totaltime = toc;

PLOTANG(I,O) % PLOTTING FOLD ANGLES

PLOTCONF(I,O) % PLOTTING CONFIGURATIONS

cd ..  % CHANGING DIRECTORY BACK